/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.donor;

import business.enterprise.Enterprise;
import business.enterprise.donation.Donor;
import business.useraccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author rohan
 */
public class DonorWorkAreaJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer; 
    Enterprise enterprise; 
    Donor donor;
    /**
     * Creates new form DonorJPanel
     */
    public DonorWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise, UserAccount account) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        donor = account.getDonor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnViewDonations = new javax.swing.JButton();
        btnPerInfo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        btnViewDonations.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnViewDonations.setText("View Donations");
        btnViewDonations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDonationsActionPerformed(evt);
            }
        });

        btnPerInfo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPerInfo.setText("Personal Information");
        btnPerInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerInfoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setText("Donor Work Area");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnPerInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnViewDonations, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnViewDonations)
                .addGap(18, 18, 18)
                .addComponent(btnPerInfo)
                .addContainerGap(397, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPerInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerInfoActionPerformed
        DonorPersonalInformationJPanel dpijp = new DonorPersonalInformationJPanel(userProcessContainer, donor, false);
        userProcessContainer.add("donorPersonalInfoJPanel", dpijp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnPerInfoActionPerformed

    private void btnViewDonationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDonationsActionPerformed
        ViewDonorDonations viewDonorDonations = new ViewDonorDonations(userProcessContainer, enterprise, donor);
        userProcessContainer.add("viewDonorDonations", viewDonorDonations);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewDonationsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPerInfo;
    private javax.swing.JButton btnViewDonations;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
