/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.statistics;

import business.enterprise.Enterprise;
import business.enterprise.donation.Donation;
import business.project.Project;
import business.victim.Victim;
import business.volunteer.Volunteer;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author rohan
 */
public class EnterpriseLevelAnalysisJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;

    /**
     * Creates new form EnterpriseLevelAnalysisJPanel
     */
    public EnterpriseLevelAnalysisJPanel(JPanel userProcessContainer, Enterprise enterprise) {

        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        getTotalDonationsPerMonth();
        getNoOfVolunteersWorkingPerProject();
        getVolunteerToVictimRatio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        donationPerMonthJPanel = new javax.swing.JPanel();
        volunteersWorkingJPanel = new javax.swing.JPanel();
        volToVitctimJPanel = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();

        donationPerMonthJPanel.setBackground(new java.awt.Color(255, 255, 255));
        donationPerMonthJPanel.setLayout(new java.awt.BorderLayout());

        volunteersWorkingJPanel.setBackground(new java.awt.Color(255, 255, 255));
        volunteersWorkingJPanel.setForeground(new java.awt.Color(255, 255, 255));
        volunteersWorkingJPanel.setLayout(new java.awt.BorderLayout());

        volToVitctimJPanel.setBackground(new java.awt.Color(255, 255, 255));
        volToVitctimJPanel.setLayout(new java.awt.BorderLayout());

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(donationPerMonthJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(volunteersWorkingJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(volToVitctimJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(volunteersWorkingJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(volToVitctimJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(donationPerMonthJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBack)
                .addContainerGap(543, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void getTotalDonationsPerMonth() {

        DefaultCategoryDataset barchartdata = new DefaultCategoryDataset();
        int donationInCurrent = 0;
        int donationInPreviousMonth = 0;
        int donation2MonthsBefore = 0;
        if (enterprise.getDonationHistory().getDonationDirectory() != null && enterprise.getDonationHistory().getDonationDirectory().size() > 0) {
            for (Donation donation : enterprise.getDonationHistory().getDonationDirectory()) {
                Date dateDonation = donation.getDonationDate();
                Date date = new Date();
                if (dateDonation.getYear() == date.getYear()) {
                    if (dateDonation.getMonth() == date.getMonth()) {
                        donationInCurrent = donationInCurrent + donation.getDonationAmount();
                        
                    }
                    if (dateDonation.getMonth() == (date.getMonth() - 1)) {
                        donationInPreviousMonth = donationInPreviousMonth + donation.getDonationAmount();
                        
                    }
                    if (dateDonation.getMonth() == (date.getMonth() - 2)) {
                        donation2MonthsBefore = donation2MonthsBefore + donation.getDonationAmount();
                        
                    }
                }
            }
        }
        barchartdata.setValue(donationInCurrent, "Donations in Current Month", "Current Month");
        barchartdata.setValue(donationInPreviousMonth, "Donations in Previous Month", "Previous Month");
        barchartdata.setValue(donation2MonthsBefore, "Donations two Months before", "Two Months before");
        JFreeChart barchart = ChartFactory.createBarChart("Number of Donations past three months", "In year 2016", "Donations", barchartdata, PlotOrientation.VERTICAL, false, true, false);
//        //       CategoryPlot barchrt = (CategoryPlot) barchart.getPlot();

        ChartPanel barchartPanel = new ChartPanel(barchart);
        donationPerMonthJPanel.removeAll();
        donationPerMonthJPanel.add(barchartPanel);
        donationPerMonthJPanel.validate();

    }

    private void getNoOfVolunteersWorkingPerProject() {

        DefaultCategoryDataset barchartdata = new DefaultCategoryDataset();
        ArrayList<Project> projects = enterprise.getProjectDirectory().getProjectList();
        
        if (projects != null && projects.size() > 0) {
            for (Project project : projects) {
                ArrayList<Volunteer> volunteers = project.getVolunteers();
                barchartdata.setValue(volunteers.size(), "Number of Volunteers", project.getProjectName());
            }

        }
        JFreeChart barchart = ChartFactory.createBarChart("Number of volunteers in each Project", "In year 2016", "Volunteers", barchartdata, PlotOrientation.VERTICAL, false, true, false);
        //       CategoryPlot barchrt = (CategoryPlot) barchart.getPlot();

        ChartPanel barchartPanel = new ChartPanel(barchart);
        volunteersWorkingJPanel.removeAll();
        volunteersWorkingJPanel.add(barchartPanel);
        volunteersWorkingJPanel.validate();
    }

    private void getVolunteerToVictimRatio() {

//        volToVitctimJPanel
        DefaultCategoryDataset barchartdata = new DefaultCategoryDataset();
        ArrayList<Project> projects = enterprise.getProjectDirectory().getProjectList();
        for (Project project : projects) {
            float volunteerToVictimRatio = 0;
            ArrayList<Victim> victims = project.getVictimDirectory().getVictimList();
            ArrayList<Volunteer> volunteers = project.getVolunteers();
            if (volunteers.size() > 0) {
                volunteerToVictimRatio =   (float)victims.size()/(float)volunteers.size();
            }
            barchartdata.setValue(volunteerToVictimRatio, "Victims to Volunteer Ratio", project.getProjectName());
        }

        
        JFreeChart barchart = ChartFactory.createBarChart("Victims to Volunteer ratio in each Project", "In year 2016", "Volunteers/Victims", barchartdata, PlotOrientation.VERTICAL, false, true, false);


        ChartPanel barchartPanel = new ChartPanel(barchart);
        volToVitctimJPanel.removeAll();
        volToVitctimJPanel.add(barchartPanel);
        volToVitctimJPanel.validate();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JPanel donationPerMonthJPanel;
    private javax.swing.JPanel volToVitctimJPanel;
    private javax.swing.JPanel volunteersWorkingJPanel;
    // End of variables declaration//GEN-END:variables
}
